## RNN

In [5]:
import numpy as np
X = np.array([[1,2,3],[2,3,4]])
y = np.sum(X, axis=1)

print("Input:\n", X)
print("Output (sum):", y)

Input:
 [[1 2 3]
 [2 3 4]]
Output (sum): [6 9]


## CNN

In [6]:
import numpy as np

image = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

kernel = np.array([
    [1,0],
    [0,-1]
])

result = np.zeros((2,2))

for i in range(2):
    for j in range(2):
        result[i,j] = np.sum(image[i:i+2, j:j+2] * kernel)

print("Convolution Output:\n", result)

Convolution Output:
 [[-4. -4.]
 [-4. -4.]]
