In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1,2,3],[4,5,6]])

print("1D Array:", a)

print("2D Array:\n", b)

print("Shape:", b.shape)

print("Zeros:\n", np.zeros((2,2)))

print(np.eye(2))

print(arr[:2,1:3])

print(np.dot(x,y))

print(x.T)

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

print(np.random.random((2,2)))

print(x + y)
print(x - y)
print(x * y)
print(x / y)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Zeros:
 [[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[2 3]
 [5 6]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
10
[4 6]
[3 7]
[[0.40744266 0.49784116]
 [0.5919025  0.69314074]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
